/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check alias
         * @description Documented compatibility alias for root/load-balancer liveness probes.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Primary health liveness endpoint returning HTTP 200 with status ok.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System readiness and diagnostic status
         * @description Returns public diagnostic status without exposing sensitive credentials.
         */
        get: operations["system_status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DatabaseStatus
         * @description Database connection and migration state.
         */
        DatabaseStatus: {
            /** Status */
            status: string;
            /** Migration Version */
            migration_version?: string | null;
        };
        /**
         * HealthResponse
         * @description Liveness probe response.
         */
        HealthResponse: {
            /**
             * Status
             * @description Service liveness state
             * @default ok
             */
            status: string;
        };
        /**
         * SystemStatusResponse
         * @description Readiness and diagnostic status information without sensitive data.
         */
        SystemStatusResponse: {
            /**
             * Status
             * @description Readiness status ('ready' or 'degraded')
             */
            status: string;
            /**
             * Version
             * @description AgentShield version
             */
            version: string;
            /**
             * Platform
             * @description Host platform identifier
             */
            platform: string;
            /**
             * Profile
             * @description Active security profile
             */
            profile: string;
            /**
             * Host
             * @description Bound host interface
             */
            host: string;
            /**
             * Port
             * @description Bound network port
             */
            port: number;
            /** @description Database connectivity status */
            database: components["schemas"]["DatabaseStatus"];
            /**
             * Frontend Available
             * @description Whether frontend static assets are built
             */
            frontend_available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    system_status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
}
