"""RFC 7807 Problem Details error definitions and exception hierarchy."""

from typing import Any

from fastapi import Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from agentshield.core.logging import get_logger, sanitize_text

logger = get_logger("agentshield.errors")


class ProblemDetails(BaseModel):
    """RFC 7807 compliant problem details model."""

    type: str = Field(
        default="urn:agentshield:error:generic",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(description="A short, human-readable summary of the problem type.")
    status: int = Field(description="The HTTP status code generated by the origin server.")
    detail: str = Field(description="A human-readable explanation specific to this occurrence.")
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem.",
    )
    invalid_params: list[dict[str, Any]] | None = Field(
        default=None,
        description="Validation error parameters if applicable.",
    )


class AgentShieldError(Exception):
    """Base exception class for all AgentShield errors."""

    def __init__(
        self,
        detail: str,
        title: str = "AgentShield Error",
        status_code: int = 500,
        error_type: str = "urn:agentshield:error:internal",
        instance: str | None = None,
        invalid_params: list[dict[str, Any]] | None = None,
    ) -> None:
        super().__init__(detail)
        self.detail = sanitize_text(detail)
        self.title = title
        self.status_code = status_code
        self.error_type = error_type
        self.instance = instance
        self.invalid_params = invalid_params

    def to_problem_details(self, instance: str | None = None) -> ProblemDetails:
        return ProblemDetails(
            type=self.error_type,
            title=self.title,
            status=self.status_code,
            detail=self.detail,
            instance=self.instance or instance,
            invalid_params=self.invalid_params,
        )


class AuthenticationError(AgentShieldError):
    """Raised when authentication credentials are missing or invalid."""

    def __init__(self, detail: str = "Invalid or missing administrative token") -> None:
        super().__init__(
            detail=detail,
            title="Unauthorized",
            status_code=401,
            error_type="urn:agentshield:error:unauthorized",
        )


class AuthorizationError(AgentShieldError):
    """Raised when access to a resource is forbidden."""

    def __init__(self, detail: str = "Access forbidden") -> None:
        super().__init__(
            detail=detail,
            title="Forbidden",
            status_code=403,
            error_type="urn:agentshield:error:forbidden",
        )


class InvalidHostError(AgentShieldError):
    """Raised when Host header does not match allowed loopback bindings."""

    def __init__(self, detail: str = "Invalid Host header") -> None:
        super().__init__(
            detail=detail,
            title="Invalid Host Header",
            status_code=400,
            error_type="urn:agentshield:error:invalid-host",
        )


class InvalidOriginError(AgentShieldError):
    """Raised when Origin header fails loopback CORS validation."""

    def __init__(self, detail: str = "Origin not allowed") -> None:
        super().__init__(
            detail=detail,
            title="Invalid Origin",
            status_code=403,
            error_type="urn:agentshield:error:invalid-origin",
        )


class NotFoundError(AgentShieldError):
    """Raised when a requested resource is not found."""

    def __init__(self, detail: str = "Resource not found") -> None:
        super().__init__(
            detail=detail,
            title="Not Found",
            status_code=404,
            error_type="urn:agentshield:error:not-found",
        )


class ConflictError(AgentShieldError):
    """Raised when a conflict occurs (e.g. port already bound)."""

    def __init__(self, detail: str = "Conflict") -> None:
        super().__init__(
            detail=detail,
            title="Conflict",
            status_code=409,
            error_type="urn:agentshield:error:conflict",
        )


class MissingCredentialError(AgentShieldError):
    """Raised when upstream provider credentials are missing."""

    def __init__(self, provider: str) -> None:
        super().__init__(
            detail=(
                f"Missing upstream credentials for provider '{provider}'. "
                "Please configure provider API key."
            ),
            title="Missing Provider Credentials",
            status_code=500,
            error_type="urn:agentshield:error:missing-credential",
        )


class ProxyLoopError(AgentShieldError):
    """Raised when a self-referential proxy request loop is detected."""

    def __init__(
        self,
        detail: str = "Proxy loop detected: request targets AgentShield proxy endpoint.",
    ) -> None:
        super().__init__(
            detail=detail,
            title="Loop Detected",
            status_code=508,
            error_type="urn:agentshield:error:loop-detected",
        )


class StreamingNotSupportedError(AgentShieldError):
    """Raised when streaming is requested in Milestone 2."""

    def __init__(
        self,
        detail: str = (
            "Streaming proxying ('stream: true') is not supported in Milestone 2. "
            "Scheduled for Milestone 4."
        ),
    ) -> None:
        super().__init__(
            detail=detail,
            title="Streaming Not Supported",
            status_code=400,
            error_type="urn:agentshield:error:streaming-not-supported",
        )


class GatewayTimeoutError(AgentShieldError):
    """Raised when upstream provider connection or response times out."""

    def __init__(self, detail: str = "Upstream provider request timed out.") -> None:
        super().__init__(
            detail=detail,
            title="Gateway Timeout",
            status_code=504,
            error_type="urn:agentshield:error:gateway-timeout",
        )


class BadGatewayError(AgentShieldError):
    """Raised when upstream provider connection fails unexpectedly."""

    def __init__(self, detail: str = "Failed to connect to upstream provider.") -> None:
        super().__init__(
            detail=detail,
            title="Bad Gateway",
            status_code=502,
            error_type="urn:agentshield:error:bad-gateway",
        )


class PayloadTooLargeError(AgentShieldError):
    """Raised when incoming request payload exceeds max allowed size."""

    def __init__(self, detail: str = "Request payload exceeds maximum allowed size.") -> None:
        super().__init__(
            detail=detail,
            title="Payload Too Large",
            status_code=413,
            error_type="urn:agentshield:error:payload-too-large",
        )


class UnsupportedContentEncodingError(AgentShieldError):
    """Raised when a request uses a content coding the proxy cannot inspect safely."""

    def __init__(self) -> None:
        super().__init__(
            detail="Request Content-Encoding is not supported.",
            title="Unsupported Content Encoding",
            status_code=415,
            error_type="urn:agentshield:error:unsupported-content-encoding",
        )


class InvalidCompressedContentError(AgentShieldError):
    """Raised when a supported compressed request body is malformed."""

    def __init__(self) -> None:
        super().__init__(
            detail="Request body is not valid compressed content.",
            title="Invalid Compressed Content",
            status_code=400,
            error_type="urn:agentshield:error:invalid-compressed-content",
        )


async def agentshield_error_handler(request: Request, exc: AgentShieldError) -> JSONResponse:
    """FastAPI exception handler for AgentShield errors returning RFC 7807 JSON."""
    problem = exc.to_problem_details(instance=str(request.url.path))
    return JSONResponse(
        status_code=problem.status,
        content=problem.model_dump(exclude_none=True),
        headers={"Content-Type": "application/problem+json"},
    )


async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """FastAPI handler for unexpected exceptions ensuring safe RFC 7807 responses without leaks."""
    logger.error("Unhandled exception processing request %s: %s", request.url.path, str(exc))
    problem = ProblemDetails(
        type="urn:agentshield:error:internal",
        title="Internal Server Error",
        status=500,
        detail="An unexpected internal error occurred.",
        instance=str(request.url.path),
    )
    return JSONResponse(
        status_code=500,
        content=problem.model_dump(exclude_none=True),
        headers={"Content-Type": "application/problem+json"},
    )
